spring:

  profiles:
    active: local # 기본적으로 local이 선택된다는 뜻

  mvc:
    view:
      prefix:
      suffix: 

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1 :3306/board?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC # DB명 치환
    username: root # DB아이디 치환
    password:

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create

  devtools:
    livereload:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

---

spring:
  profiles: local
server:
  port: 8085 # 포트번호 치환

